---
abstract: 'Wrapper to create text file using the CGI syntax'
author:
  - 'celogeek <me@celogeek.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.010
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CGILike
requires:
  Carp: 0
  Moo: 0
  Text::Format: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/celogeek/Text-CGILike/issues
  homepage: https://github.com/celogeek/Text-CGILike
  repository: https://github.com/celogeek/Text-CGILike
version: 0.6
x_Dist_Zilla:
  perl:
    version: 5.018002
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::Celogeek/Git::NextVersion'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::Celogeek/NextRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::Celogeek/@Git/Check'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::Celogeek/@Git/Commit'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::Celogeek/@Git/Tag'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::Celogeek/@Git/Push'
      version: 2.019
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::Celogeek/@Filter/GatherDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::Celogeek/@Filter/PruneCruft'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::Celogeek/@Filter/ManifestSkip'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::Celogeek/@Filter/MetaYAML'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::Celogeek/@Filter/License'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::Celogeek/@Filter/Readme'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::Celogeek/@Filter/ExtraTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::Celogeek/@Filter/ExecDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::Celogeek/@Filter/ShareDir'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::Celogeek/@Filter/Manifest'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::Celogeek/@Filter/TestRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::Celogeek/@Filter/ConfirmRelease'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::Celogeek/@Filter/UploadToCPAN'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::Celogeek/ModuleBuild'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@Author::Celogeek/ReportVersions'
      version: 1.110730
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: '@Author::Celogeek/OurPkgVersion'
      version: 0.005000
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::Celogeek/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::Celogeek/AutoPrereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: '@Author::Celogeek/Prereqs'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::Celogeek/MinimumPerl'
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::Celogeek/Test::Compile'
      version: 2.039
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::Celogeek/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@Author::Celogeek/Test::UnusedVars'
      version: 2.000005
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::Celogeek/PodCoverageTests'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::Celogeek/PruneFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::ReadmeMarkdownFromPod
      name: '@Author::Celogeek/ReadmeMarkdownFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::Celogeek/MetaJSON'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: '@Author::Celogeek/MetaResourcesFromGit'
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::Celogeek/MetaConfig'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugin: '@Celogeek'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: 4.004
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: 4.004
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: 4.004
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: 4.004
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: 4.004
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: 4.004
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: 4.004
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: 4.004
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: 4.004
            -
              class: Pod::Weaver::Section::Bugs
              name: '@Default/Bugs'
              version: 4.004
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: 4.004
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: 4.004
      name: '@Author::Celogeek/PodWeaver'
      version: 4.002
    -
      class: Dist::Zilla::Plugin::Run::BeforeRelease
      name: '@Author::Celogeek/Run::BeforeRelease'
      version: 0.020
    -
      class: Dist::Zilla::Plugin::PerlTidy
      name: '@Author::Celogeek/PerlTidy'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::Celogeek/Test::Perl::Critic'
      version: 2.112410
    -
      class: Dist::Zilla::Plugin::MetaResourcesFromGit
      name: MetaResourcesFromGit
      version: 1.103620
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 5.006
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 5.006
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 5.006
